### ISSUE TITLE
Try video file if audio can't be found

### ISSUE THREAD

**Issue by OpenHypervideo** [OpenParliamentTV/OpenParliamentTV-Tools#7]
During the audio alignment, sometimes the mp3 file can't be found (for a few speeches it has never been published). In that case
we get an error: 
```
ERROR DE.aligner.align_sentences 
Cannot download https://static.p.core.cdn.streamfarm.net/1000153copo/ondemand/145293313/7546262/7546262_mp3_128kb_stereo_de_128.mp3: 
HTTP Error 404: Not Found
```
As Aeneas also works with mp4 files as input (with the same parameters), could we change  
[this](https://github.com/OpenParliamentTV/OpenParliamentTV-Tools/blob/main/optv/parliaments/DE/aligner/align_sentences.py#L101) to also try the `videoFileURI` before it entirely fails (one of the two should be there, I know of only one very special case where neither mp3 nor mp4 are present)?

**Comment by tammo0** [comment]
FYI: There are more cases where neither the mp3 nor the mp4 is available.
For example: 20EP, 73 Session: 7548905, 7548851; 20EP, 55 Session: 7546262, 7546245, ...
The streams ("sourcePage") for these speeches seems to work fine

**Comment by OpenHypervideo** [comment]
Maybe another URL works for the MP3 or MP4 files? There are almost always two URLs (static and cloud?). 
Maybe we also need to check the second URL structure in case the first comes back with a 404?

VIDEO URLS:

--> Download available from the 17. Electoral Period (27.10.2009)

PART 1:
`https://cldf-od.r53.cdn.tv1.eu/1000153copo/ondemand/app144277506/`
`https://static.p.core.cdn.streamfarm.net/1000153copo/ondemand/`

PART 2:
`145293313/`

PART 3:
`$MEDIAID/$MEDIAID_h264_720_576_2000kb_de_2192.mp4`    (17. EP)
`$MEDIAID/$MEDIAID_h264_720_400_2000kb_baseline_de_2192.mp4`    (from 18. EP)


AUDIO URLS:

--> Download available from the 18. Electoral Period (22.10.2013)

PART 1:
`https://cldf-od.r53.cdn.tv1.eu/1000153copo/ondemand/app144277506/`
`https://static.p.core.cdn.streamfarm.net/1000153copo/ondemand/`

PART 2:
`145293313/ `

Part 3:
`$MEDIAID/$MEDIAID_mp3_128kb_stereo_de_128.mp3`

**Comment by oaubert** [comment]
I fixed the initial issue (try to fallback on videoFileURI if audioFileURI is not found). The other case mentionned by @tammo0 is not related to the alignment IMO, but rather to media/proceeding parsing: the adequate information (audio and/or video) should be stored in the session file.
